version: '3.7'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./tailwind.config.cjs:/app/tailwind.config.cjs
      - ./postcss.config.cjs:/app/postcss.config.cjs
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./.typesafe-i18n.json:/app/.typesafe-i18n.json
      - ./index.html:/app/index.html
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_KEYCLOAK_URL_AUTH=${VITE_KEYCLOAK_URL_AUTH}
      - VITE_KEYCLOAK_REALM=${VITE_KEYCLOAK_REALM}
      - VITE_KEYCLOAK_CLIENT=${VITE_KEYCLOAK_CLIENT}
      - VITE_BASE_URL_API=${VITE_BASE_URL_API}
      - VITE_KEYCLOAK_API=${VITE_KEYCLOAK_API}
