version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=local
      - DATABASE_URL=${DATABASE_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKETNAME=${MINIO_BUCKETNAME}
      - FLUENTD_HOST=${FLUENTD_HOST}
      - FLUENTD_PORT=${FLUENTD_PORT}
      - FLUENTD_TIMEOUT=${FLUENTD_TIMEOUT}
      - FLUENTD_RECONNECT_INTERVAL=${FLUENTD_RECONNECT_INTERVAL}
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./test:/app/test
      - ./prisma:/app/prisma
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules

  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: db
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password


volumes:
  postgres_data:
      driver: local