FROM node:16-alpine

ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add --update --no-cache py3-numpy py3-pandas py3-openpyxl
WORKDIR /app

# set environment db variable
ENV DATABASE_URL=

# set NODE_ENV var
ENV NODE_ENV=

# install app dependencies
COPY package.json /app
RUN yarn install

# run app
CMD NODE_ENV=${NODE_ENV} && echo "MINIO_BUCKETNAME=${MINIO_BUCKETNAME}" > .env && echo "MINIO_SECRET_KEY=${MINIO_SECRET_KEY}" >> .env && echo "MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}" >> .env && echo "MINIO_PORT=${MINIO_PORT}" >> .env && echo "MINIO_ENDPOINT=${MINIO_ENDPOINT}" >> .env && echo "DATABASE_URL=${DATABASE_URL}" >> .env && echo "FLUENTD_HOST=${FLUENTD_HOST}" >> .env && echo "FLUENTD_PORT=${FLUENTD_PORT}" >> .env && echo "FLUENTD_TIMEOUT=${FLUENTD_TIMEOUT}" >> .env && echo "FLUENTD_RECONNECT_INTERVAL=${FLUENTD_RECONNECT_INTERVAL}" >> .env && npx prisma migrate deploy && yarn start
