apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: motower-ihm
  name: backend-ihm
  labels:
    app: backend-ihm
spec:
  selector:
    matchLabels:
      app: backend-ihm
  template:
    metadata:
      labels:
        app: backend-ihm
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend-ihm
          image: system.registry.eneci.net/oci-backend:latest #Change this image according your env
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "npx prisma db seed"]
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "500Mi"
          env:
            - name: MINIO_ENDPOINT
              value:  system.minioapi.eneci.net
            - name: MINIO_PORT
              value: "443" #Change this value according your env
            - name: MINIO_ACCESS_KEY
              value: motower #Change this value according your env
            - name: MINIO_SECRET_KEY
              value: 6Sfa6MTpt96dY2D9Jv5c #Change this value according your env
            - name: MINIO_BUCKETNAME
              value: motower
            - name: DATABASE_URL
              value: postgresql://motower:6Sfa6MTpt96dY2D9Jv5c@postgres-postgresql:5432/ihm_db?schema=public
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: motower-ihm
  name: backend-ihm-svc
spec:
  type: NodePort
  selector:
    app: backend-ihm
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30010
