apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: motower-ihm
  name: backend-ihm
  labels:
    app: backend-ihm
spec:
  selector:
    matchLabels:
      app: backend-ihm
  template:
    metadata:
      labels:
        app: backend-ihm
    spec:
      containers:
        - name: backend-ihm
          image: almoustapha/gps-oci-api:oci #Change this image according your env
          imagePullPolicy: Always
          env:
            - name: MINIO_ENDPOINT
              value: datastack-minio.data-stack #Change this value according your env
            - name: MINIO_PORT
              value: 9000 #Change this value according your env
            - name: MINIO_ACCESS_KEY
              value: RAacjEMGZIrn2IYd #Change this value according your env
            - name: MINIO_SECRET_KEY
              value: ChtN4yCj58MTpUrnbdj5Rlkm4lt57jPx #Change this value according your env
            - name: MINIO_BUCKETNAME
              value: motower
            - name: DATABASE_URL
              value: postgresql://motower:6Sfa6MTpt96dY2D9Jv5c@postgres-postgresql:5432/ihm_db?schema=public
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: motower-ihm
  name: backend-ihm-svc
spec:
  type: NodePort
  selector:
    app: backend-ihm
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30010