apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: motower-ihm
  name: backend-ihm
  labels:
    app: backend-ihm
spec:
  selector:
    matchLabels:
      app: backend-ihm
  template:
    metadata:
      labels:
        app: backend-ihm
    spec:
      containers:
        - name: backend-ihm
          image: almoustapha/gps-oci-api:oci #Change this image according your env
          imagePullPolicy: Always
          env:
            - name: MINIO_ENDPOINT
              value: datastack-minio.default #Change this value according your env
            - name: MINIO_PORT
              value: 9000 #Change this value according your env
            - name: MINIO_ACCESS_KEY
              value: RAacjEMGZIrn2IYd #Change this value according your env
            - name: MINIO_SECRET_KEY
              value: ChtN4yCj58MTpUrnbdj5Rlkm4lt57jPx #Change this value according your env
            - name: MINIO_BUCKETNAME
              value: motower
            - name: DATABASE_URL
              value: postgresql://motower:6Sfa6MTpt96dY2D9Jv5c@postgres:5432/ihm_db?schema=public
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: motower-ihm
  name: backend-ihm-svc
spec:
  selector:
    app: backend-ihm
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: motower-ihm
  name: backend-ihm-ingress
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: nginx
  rules:
    - host: 10.242.36.139.sslip. #Change this value according your env
      http:
        paths:
          - backend:
              service:
                name: backend-ihm-svc
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
