apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: motower
  name: frontend-ihm
  labels:
    app: frontend-ihm
spec:
  selector:
    matchLabels:
      app: frontend-ihm
  template:
    metadata:
      labels:
        app: frontend-ihm
    spec:
      containers:
        - name: frontend-ihm
          image: almoustapha/gps-oci-api:oci #Change this image according your env
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: motower
  name: frontend-ihm-svc
spec:
  selector:
    app: frontend-ihm
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: motower
  name: frontend-ihm-ingress
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: nginx
  rules:
    - host: 10.242.36.138.sslip.io #Change this value according your env
      http:
        paths:
          - backend:
              service:
                name: frontend-ihm-svc
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
