-- AlterTable
ALTER TABLE "file_user" ADD COLUMN     "last_modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "name" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "size" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "url" TEXT NOT NULL DEFAULT '';
